[project]
name = "aignx-platform-client"
version = "0.1.0"
description = "Client library for the Aignostics Platform API"
#authors = ["Aignostics GmbH <info@aignostics.com>"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "codegen"
]

[tool.uv.sources]
codegen = { path = "true" }

[tool.uv.workspace]
members = ["packages/*"]
#exclude = ["codegen/docs"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
