#[tool.pyright]
#venvPath = "."
#venv = ".venv"
#include = ["src", "codegen"]
#pythonVersion = "3.12"
#executionEnvironments = [{ root = ".", extraPaths = ["codegen"] }]

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aignostics_platform_client"
version = "0.1.0"
description = "Client library for the Aignostics Platform API"
authors = ["Aignostics GmbH <info@aignostics.com>"]
readme = "README.md"
packages = [
    { include = "aignx", from = "src" },
    { include = "aignx", from = "codegen" },
    { include = "aignx", from = "tests" },
]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
pydantic = "^2.9.2"
typing-extensions = ">=4.13.0"
python-dateutil = "^2.9.0.post0"
urllib3 = "^2.2.3"
requests-oauthlib = "^2.0.0"
requests = "^2.32.3"
httpx = "^0.28.1"
tifffile = "^2025.1.10"
pyrfc6266 = "^1.0.2"
tqdm = "^4.67.1"
jsonschema = "4.23.0"
google-crc32c = "1.7.1"
google-cloud-storage = "3.1.0"
pyjwt = "2.10.1"
#keyring = "25.6.0"
# to temp. store the tokens in the cache folder
appdirs = "1.4.4"
python-dotenv = "1.1.0"
jsf = "0.11.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-cov = "^6.0.0"
pytest-timeout = "2.3.1"


[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "requirements: mark tests with ids (e.g., PAPI-123, HETA-123) of requirements in Jira. The test will be linked to them - optional; comma-separated",
    "specifications: mark test with ids (e.g., PAPI-123, HETA-123) of specifications in Jira. The test will be linked to them - optional; comma-separated",
    "labels: mark test with labels that are attached to the test tickets in Jira - optional; comma-separated",
    "description: textual description what the test does, goes in `description` field in the Jira ticket - optional"
]
