coverage:
  range: "70...75"
  status:
    project:
      default:
        target: 70%
        informational: false
    patch:
      default:
        target: 75%
        informational: false

flags:
  ci:
    carryforward: false
  scheduled_staging:
    carryforward: true
  scheduled_production:
    carryforward: true
