services:
  aignostics:
    build: .
    env_file:
      - path: .env
        required: true
    develop:
      watch:
        - path: src
          action: rebuild
        - path: codegen
          action: rebuild
    restart: no
    profiles:
      - manual
    tty: true
    stdin_open: true
