Traceback (most recent call last):
  File "/Users/helmut/Code/opt/.nox/docs-3-13/bin/aignostics", line 4, in <module>
    from aignostics.cli import cli
  File "/Users/helmut/Code/opt/src/aignostics/cli.py", line 7, in <module>
    import typer
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/typer/__init__.py", line 7, in <module>
    from click.exceptions import Abort as Abort
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/click/__init__.py", line 8, in <module>
    from .core import Argument as Argument
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1155, in get_code
  File "<frozen importlib._bootstrap_external>", line 784, in _compile_bytecode
KeyboardInterrupt
