Traceback (most recent call last):
  File "/Users/helmut/Code/opt/.nox/docs-3-13/bin/aignostics", line 4, in <module>
    from aignostics.cli import cli
  File "/Users/helmut/Code/opt/src/aignostics/cli.py", line 8, in <module>
    import uvicorn
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/uvicorn/__init__.py", line 2, in <module>
    from uvicorn.main import Server, main, run
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/uvicorn/main.py", line 33, in <module>
    from uvicorn.supervisors import ChangeReload, Multiprocess
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/uvicorn/supervisors/__init__.py", line 12, in <module>
    from uvicorn.supervisors.watchfilesreload import WatchFilesReload as ChangeReload
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/uvicorn/supervisors/watchfilesreload.py", line 7, in <module>
    from watchfiles import watch
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/watchfiles/__init__.py", line 2, in <module>
    from .main import Change, awatch, watch
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/watchfiles/main.py", line 9, in <module>
    import anyio
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/anyio/__init__.py", line 3, in <module>
    from ._core._eventloop import current_time as current_time
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/anyio/_core/_eventloop.py", line 11, in <module>
    import sniffio
  File "/Users/helmut/Code/opt/.nox/docs-3-13/lib/python3.13/site-packages/sniffio/__init__.py", line 10, in <module>
    from ._version import __version__
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1559, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1533, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1660, in find_spec
  File "<frozen importlib._bootstrap_external>", line 133, in _path_join
KeyboardInterrupt
