
"""
Aignostics Platform API

Pagination is done via `page` and `page_size`. Sorting via `sort` query parameter. sort is a comma-separated list of field names. The sorting direction can be indicated via `+` (ascending) or `-` (descending) (e.g. `/applications?sort=+name)`.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum
from typing import Self


class ArtifactEvent(str, Enum):
    """
    This is a subset of the OutputArtifactEvent used by the state machine. Only the variants defined below are allowed to be submitted from the Algorithms/Applications.
    """

    """
    allowed enum values
    """
    SUCCEEDED = "succeeded"
    FAILED_WITH_USER_ERROR = "failed_with_user_error"
    FAILED_WITH_SYSTEM_ERROR = "failed_with_system_error"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ArtifactEvent from a JSON string"""
        return cls(json.loads(json_str))
