
"""
Aignostics Platform API

Pagination is done via `page` and `page_size`. Sorting via `sort` query parameter. sort is a comma-separated list of field names. The sorting direction can be indicated via `+` (ascending) or `-` (descending) (e.g. `/applications?sort=+name)`.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictStr

from aignx.codegen.models.application_run_status import ApplicationRunStatus
from aignx.codegen.models.user_payload import UserPayload


class RunReadResponse(BaseModel):
    """
    RunReadResponse
    """
    application_run_id: StrictStr
    application_version_id: StrictStr
    organization_id: StrictStr
    user_payload: UserPayload | None = None
    status: ApplicationRunStatus
    triggered_at: datetime
    triggered_by: StrictStr
    __properties: ClassVar[list[str]] = ["application_run_id", "application_version_id", "organization_id", "user_payload", "status", "triggered_at", "triggered_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of RunReadResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_payload
        if self.user_payload:
            _dict["user_payload"] = self.user_payload.to_dict()
        # set to None if user_payload (nullable) is None
        # and model_fields_set contains the field
        if self.user_payload is None and "user_payload" in self.model_fields_set:
            _dict["user_payload"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of RunReadResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "application_run_id": obj.get("application_run_id"),
            "application_version_id": obj.get("application_version_id"),
            "organization_id": obj.get("organization_id"),
            "user_payload": UserPayload.from_dict(obj["user_payload"]) if obj.get("user_payload") is not None else None,
            "status": obj.get("status"),
            "triggered_at": obj.get("triggered_at"),
            "triggered_by": obj.get("triggered_by")
        })
        return _obj
