
"""
Aignostics Platform API

Pagination is done via `page` and `page_size`. Sorting via `sort` query parameter. sort is a comma-separated list of field names. The sorting direction can be indicated via `+` (ascending) or `-` (descending) (e.g. `/applications?sort=+name)`.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictStr

from aignx.codegen.models.input_artifact_schema_creation_request import InputArtifactSchemaCreationRequest
from aignx.codegen.models.output_artifact_schema_creation_request import OutputArtifactSchemaCreationRequest


class VersionCreationRequest(BaseModel):
    """
    VersionCreationRequest
    """
    version: StrictStr
    application_id: StrictStr
    flow_id: StrictStr
    changelog: StrictStr
    input_artifacts: list[InputArtifactSchemaCreationRequest]
    output_artifacts: list[OutputArtifactSchemaCreationRequest]
    __properties: ClassVar[list[str]] = ["version", "application_id", "flow_id", "changelog", "input_artifacts", "output_artifacts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of VersionCreationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in input_artifacts (list)
        _items = []
        if self.input_artifacts:
            for _item_input_artifacts in self.input_artifacts:
                if _item_input_artifacts:
                    _items.append(_item_input_artifacts.to_dict())
            _dict["input_artifacts"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in output_artifacts (list)
        _items = []
        if self.output_artifacts:
            for _item_output_artifacts in self.output_artifacts:
                if _item_output_artifacts:
                    _items.append(_item_output_artifacts.to_dict())
            _dict["output_artifacts"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of VersionCreationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "application_id": obj.get("application_id"),
            "flow_id": obj.get("flow_id"),
            "changelog": obj.get("changelog"),
            "input_artifacts": [InputArtifactSchemaCreationRequest.from_dict(_item) for _item in obj["input_artifacts"]] if obj.get("input_artifacts") is not None else None,
            "output_artifacts": [OutputArtifactSchemaCreationRequest.from_dict(_item) for _item in obj["output_artifacts"]] if obj.get("output_artifacts") is not None else None
        })
        return _obj
